# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trucodb
      POSTGRES_USER: trucouser
      POSTGRES_PASSWORD: trucopass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: